#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONVERT="$ROOT/run/hosts-to-inventory.sh"

fail() {
  printf 'FAIL: %s\n' "$*" >&2
  exit 1
}

run_and_capture() {
  local output status
  set +e
  output="$("$@" 2>&1)"
  status=$?
  set -e
  printf '%s\n%s' "$status" "$output"
}

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

# stdout only: the skip reports go to stderr and are asserted separately.
convert_stdout() {
  "$CONVERT" "$@" 2>/dev/null
}

assert_equals() {
  local label=$1 expected=$2 actual=$3
  [[ "$expected" == "$actual" ]] ||
    fail "$label: expected <$expected>, got <$actual>"
}

assert_status() {
  local label=$1 expected=$2 result=$3
  local status="${result%%$'\n'*}"
  local output="${result#*$'\n'}"
  [[ "$status" == "$expected" ]] ||
    fail "$label: expected status $expected, got $status: $output"
}

assert_contains() {
  local label=$1 needle=$2 haystack=$3
  [[ "$haystack" == *"$needle"* ]] ||
    fail "$label: expected to find <$needle> in <$haystack>"
}

# ---------------------------------------------------------------------------
# A realistic /etc/hosts: banner comments, tabs, several names per line, a
# trailing comment, loopback/broadcast/IPv6 noise, and two malformed lines.
# ---------------------------------------------------------------------------
hosts_file="$tmpdir/hosts"
cat >"$hosts_file" <<'EOF'
##
# Host Database
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
fe80::1%lo0	localhost

# ceph lab
192.168.18.166 ceph-lab-mon-01 mon01 mon01.lab.local   # seed
192.168.18.167	ceph-lab-mon-02	mon02
192.168.18.169  ceph-lab-osd-01 osd01

1.2.3.4 aaa aaa.com
10.0.0.9 _gateway k8s1
10.0.0.10
not-an-ip foo
EOF

expected_basic='# generated by hosts-to-inventory.sh from '"$hosts_file"'
SSH_USER="ikaros"
HOSTS=(
  "ceph-lab-mon-01=192.168.18.166"
  "ceph-lab-mon-02=192.168.18.167"
  "ceph-lab-osd-01=192.168.18.169"
  "aaa=1.2.3.4"
  "k8s1=10.0.0.9"
)'
assert_equals "basic conversion" \
  "$expected_basic" \
  "$(convert_stdout --user ikaros "$hosts_file")"

# The first name wins ("1.2.3.4 aaa aaa.com" -> aaa), an unusable first name
# falls through to the next one ("_gateway k8s1" -> k8s1), and loopback,
# broadcast and IPv6 lines never reach the output. All covered above.

# Skips are reported, never silent.
stderr_output="$("$CONVERT" --user ikaros "$hosts_file" 2>&1 >/dev/null)"
assert_contains "reports address without hostname" "10.0.0.10" "$stderr_output"
assert_contains "reports non-address line" "not-an-ip" "$stderr_output"

# ---------------------------------------------------------------------------
# Scalar assignments are emitted only when asked for.
# ---------------------------------------------------------------------------
seeded="$(convert_stdout --user ikaros --seed mon01 --rook-ns rook-a \
  --rook-operator-ns rook-b "$hosts_file")"
assert_contains "seed resolves a non-first hostname" \
  'SEED_HOST="192.168.18.166"' "$seeded"
assert_contains "rook namespace" 'ROOK_NAMESPACE="rook-a"' "$seeded"
assert_contains "rook operator namespace" \
  'ROOK_OPERATOR_NAMESPACE="rook-b"' "$seeded"

assert_contains "seed accepts an alias" 'SEED_HOST="192.168.18.167"' \
  "$(convert_stdout --user ikaros --seed ceph-lab-mon-02 "$hosts_file")"
assert_contains "seed accepts a literal address" 'SEED_HOST="192.168.18.169"' \
  "$(convert_stdout --user ikaros --seed 192.168.18.169 "$hosts_file")"

# ---------------------------------------------------------------------------
# Filters and alias shaping.
# ---------------------------------------------------------------------------
fqdn_file="$tmpdir/fqdn-hosts"
cat >"$fqdn_file" <<'EOF'
192.168.18.166 mon01.lab.local
192.168.18.169 osd01.lab.local
10.9.9.9 printer.lab.local
EOF

assert_equals "strip-domain and match" \
  '# generated by hosts-to-inventory.sh from '"$fqdn_file"'
SSH_USER="ikaros"
HOSTS=(
  "mon01=192.168.18.166"
  "osd01=192.168.18.169"
)' \
  "$(convert_stdout --user ikaros --strip-domain --match '(mon|osd)' "$fqdn_file")"

assert_contains "without strip-domain the FQDN is the alias" \
  '"mon01.lab.local=192.168.18.166"' \
  "$(convert_stdout --user ikaros --match mon01 "$fqdn_file")"

excluded="$(convert_stdout --user ikaros --strip-domain --exclude printer "$fqdn_file")"
[[ "$excluded" != *printer* ]] || fail "exclude: printer should be gone"
assert_contains "exclude keeps the rest" '"mon01=192.168.18.166"' "$excluded"

# ---------------------------------------------------------------------------
# IPv6 is opt-in and bracketed; link-local and loopback stay out.
# ---------------------------------------------------------------------------
v6_file="$tmpdir/v6-hosts"
cat >"$v6_file" <<'EOF'
fd00::10 mon01
fe80::1%eth0 linklocal
::1 localhost
ff02::1 multicast
EOF
assert_equals "ipv6 opt-in" \
  '# generated by hosts-to-inventory.sh from '"$v6_file"'
SSH_USER="ikaros"
HOSTS=(
  "mon01=[fd00::10]"
)' \
  "$(convert_stdout --user ikaros --ipv6 "$v6_file")"

assert_status "ipv6 stays out by default" 1 \
  "$(run_and_capture "$CONVERT" --user ikaros "$v6_file")"

assert_contains "keep-loopback opts loopback back in" '"localhost=127.0.0.1"' \
  "$(convert_stdout --user ikaros --keep-loopback "$hosts_file")"

# ---------------------------------------------------------------------------
# stdin.
# ---------------------------------------------------------------------------
stdin_output="$(printf '10.0.0.1 mon01\n' | convert_stdout --user ikaros -)"
assert_contains "stdin input" '"mon01=10.0.0.1"' "$stdin_output"
assert_contains "stdin provenance" 'from stdin' "$stdin_output"

# ---------------------------------------------------------------------------
# Fail closed rather than emit a wrong inventory.
# ---------------------------------------------------------------------------
collide_file="$tmpdir/collide-hosts"
printf '10.0.0.1 web.a.com\n10.0.0.2 web.b.com\n' >"$collide_file"
collide="$(run_and_capture "$CONVERT" --user ikaros --strip-domain "$collide_file")"
assert_status "alias collision fails" 1 "$collide"
assert_contains "alias collision explains itself" "maps to both" "$collide"

dup_file="$tmpdir/dup-hosts"
printf '10.0.0.1 mon01\n10.0.0.1 mon01\n10.0.0.1 other\n' >"$dup_file"
dup="$(run_and_capture "$CONVERT" --user ikaros "$dup_file")"
assert_status "repeated address is not fatal" 0 "$dup"
assert_contains "repeated entry reported" "duplicate entry" "$dup"
assert_contains "same address under a second alias reported" \
  "already collected as alias mon01" "$dup"
dup_entries="$(convert_stdout --user ikaros "$dup_file" | grep -c '^  "' || true)"
[[ "${dup_entries// /}" == "1" ]] ||
  fail "repeated address should yield exactly one HOSTS entry, got $dup_entries"

empty_file="$tmpdir/empty-hosts"
printf '# only comments\n127.0.0.1 localhost\n' >"$empty_file"
assert_status "no usable entry fails" 1 \
  "$(run_and_capture "$CONVERT" --user ikaros "$empty_file")"

assert_status "invalid user fails" 1 \
  "$(run_and_capture "$CONVERT" --user 'bad user' "$hosts_file")"
assert_status "invalid namespace fails" 1 \
  "$(run_and_capture "$CONVERT" --user ikaros --rook-ns 'bad ns' "$hosts_file")"
assert_status "invalid regex fails" 1 \
  "$(run_and_capture "$CONVERT" --user ikaros --match '(' "$hosts_file")"
assert_status "unknown option fails" 1 \
  "$(run_and_capture "$CONVERT" --definitely-not-an-option "$hosts_file")"
assert_status "missing input fails" 1 \
  "$(run_and_capture "$CONVERT" --user ikaros "$tmpdir/does-not-exist")"
assert_status "option without a value fails" 1 \
  "$(run_and_capture "$CONVERT" --user)"

# ---------------------------------------------------------------------------
# --output does not clobber an existing file without --force.
# ---------------------------------------------------------------------------
out_file="$tmpdir/out.env"
printf 'do not lose me\n' >"$out_file"
assert_status "output refuses to overwrite" 1 \
  "$(run_and_capture "$CONVERT" --user ikaros -o "$out_file" "$hosts_file")"
assert_equals "existing output untouched" "do not lose me" "$(cat "$out_file")"
assert_status "force overwrites" 0 \
  "$(run_and_capture "$CONVERT" --user ikaros -o "$out_file" --force "$hosts_file")"
assert_contains "forced output has hosts" '"ceph-lab-mon-01=192.168.18.166"' \
  "$(cat "$out_file")"

# ---------------------------------------------------------------------------
# The point of the whole script: the reference inventory parser accepts the
# output, and accepts every entry (no "skipped unsafe ..." rejects).
# ---------------------------------------------------------------------------
generated="$tmpdir/generated.env"
"$CONVERT" --user ikaros --seed mon01 --rook-ns rook-ceph "$hosts_file" \
  >"$generated" 2>/dev/null

parsed="$(
  bash -c '
    set -euo pipefail
    # shellcheck source=/dev/null
    source "$1/lib/common.sh"
    # shellcheck source=/dev/null
    source "$1/lib/bundle.sh"
    load_inventory "$2"
    printf "user=%s seed=%s ns=%s count=%s\n" \
      "$SSH_USER" "$SEED_HOST" "$ROOK_NAMESPACE" "${#HOSTS[@]}"
    for entry in "${HOSTS[@]}"; do
      alias_name=${entry%%=*}
      host=${entry#*=}
      if [[ "$alias_name" == "." || "$alias_name" == ".." ||
            ! "$alias_name" =~ ^[A-Za-z0-9][A-Za-z0-9._-]*$ ]]; then
        printf "unsafe alias: %s\n" "$alias_name"
        exit 1
      fi
      if ! is_safe_ssh_target "$(ssh_target_for_host "$host" "$SSH_USER")"; then
        printf "unsafe target: %s\n" "$host"
        exit 1
      fi
    done
  ' _ "$ROOT" "$generated"
)" || fail "generated inventory rejected by load_inventory: $parsed"

assert_equals "reference parser reads the generated inventory" \
  "user=ikaros seed=192.168.18.166 ns=rook-ceph count=5" \
  "$parsed"

# IPv6 output has to survive the same gate.
v6_generated="$tmpdir/generated-v6.env"
"$CONVERT" --user ikaros --ipv6 "$v6_file" >"$v6_generated" 2>/dev/null
bash -c '
  set -euo pipefail
  # shellcheck source=/dev/null
  source "$1/lib/common.sh"
  # shellcheck source=/dev/null
  source "$1/lib/bundle.sh"
  load_inventory "$2"
  entry=${HOSTS[0]}
  is_safe_ssh_target "$(ssh_target_for_host "${entry#*=}" "$SSH_USER")"
' _ "$ROOT" "$v6_generated" ||
  fail "generated IPv6 inventory rejected by the reference parser"

printf 'ok: hosts-to-inventory\n'
